#include 'tlpp-core.th'
#include 'tlpp-rest.th'

#Define DEFAULT_PAGESIZE 100

Namespace Albuquerque.Api

@Get("/api/products")
User Function products()
	Local jQryStr := oRest:GetQueryRequest()
	Local nCurrentPage := If( jQryStr != Nil .And. jQryStr['page'] != Nil, jQryStr['page'], 1 )

	VarInfo('jQryStr', jQryStr)
	VarInfo('nCurrentPage', nCurrentPage)
  
  	oRest:setResponse('teste')
Return .T.
